### ISSUE TITLE
Displaying progress

### ISSUE THREAD

**Issue by 74cmonty** [jbd/msrsync#1]
Hello!

I have just recently found your program and it helped me alot to shift x TB of data from A to B.

However, I would like to ask you if you can implement another feature: progress display.
I mean not a forecast, but just to know how many bytes have been transferred, and how many are still pending.

THX

**Comment by jbd** [comment]
Hello,

thank you for the feedback. I've implemented a quick'n dirty progress status in the [progress branch](https://github.com/jbd/msrsync/tree/progress) (see -P/--progress option, and also -d/--dry-run if you don't want to execute the rsync processes). 

Tell me what you think !

**Comment by 74cmonty** [comment]
Hi, 
I've downloaded the new files in "progress.zip" and extracted msrsync, but I get this error message:
error: option -P not recognized

This is the binary I use:
-rwxr-xr-x 1 root root    55693 May  2 20:46 /usr/bin/msrsync

THX

**Comment by jbd** [comment]
I guess you are not running the msrync from the progress.zip file. Run make install, or ./msrync from the extracted directory.

This works for me: 

```
$ wget https://github.com/jbd/msrsync/archive/progress.zip
[...]
$ unp progress.zip
Archive:  progress.zip
90c3b8ef59886f742d00945f0d2b3e7bb938c7c4
   creating: msrsync-progress/
  inflating: msrsync-progress/.gitignore  
  inflating: msrsync-progress/LICENSE  
  inflating: msrsync-progress/Makefile  
  inflating: msrsync-progress/README.md  
  inflating: msrsync-progress/msrsync
$ ./msrsync --help |& grep progress
    -P, --progress        show progress
```

Or,

```
$ git clone https://github.com/jbd/msrsync
[...]
$ cd msrsync/
$ git checkout progress 
$ ./msrsync --help |& grep progress
    -P, --progress        show progres
```

**Comment by jbd** [comment]
I've just spotted a bug in the progress branch (not related to your problem though), please checkout https://github.com/jbd/msrsync/commit/253c4422fc5fee4b997b643b4536c373d9c5fdac before testing progress output.

**Comment by jbd** [comment]
I've rebased everything in the master branch.

**Comment by jbd** [comment]
The progress option looks OK to me. I've got a bunch of things waiting in another branch but that should be enough to close this issue for now.

Feel free to open another if you encounter a problem with my progress implementation.
