### ISSUE TITLE
-d flag causes error

### ISSUE THREAD

**Issue by carlilek** [jbd/msrsync#10]
repro: run with -d flag. There is no else for the line that checks if it is present, so it attempts to continue with the loop without running rsync, so it throws the error below: 

Process Process-2:
Traceback (most recent call last):
  File "/misc/local/python-2.7.11/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/misc/local/python-2.7.11/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/bin/msrsync", line 824, in rsync_worker
    rsync_mon_result = {"type": TYPE_RSYNC, "rsync_result": rsync_result, "size": bucket_size, "files_nr": bucket_files_nr, "jq_size": jobs_queue.qsize()}
UnboundLocalError: local variable 'rsync_result' referenced before assignment

**Comment by jbd** [comment]
Looks like https://github.com/jbd/msrsync/issues/6

**Comment by carlilek** [comment]
Ah, my branch is undoubtedly from prior to that. Sorry!

--Ken

Sent from my <advertising redacted>

On Aug 29, 2018, at 6:04 PM, jbd <notifications@github.com<mailto:notifications@github.com>> wrote:


Looks like #6<https://github.com/jbd/msrsync/issues/6>
