### ISSUE TITLE
Exclude Directories with msrsync not working

### ISSUE THREAD

**Issue by picturethisstudio** [jbd/msrsync#17]
Hello,

Trying to add "--exclude-from=" with -r option while syncing directories with excluding few, which seems to be not working.

**Comment by jbd** [comment]
Hello,

Since you didn't provide any examples, I will guess what the problem is.

Please have a look at:

https://stackoverflow.com/a/41876294
https://github.com/jbd/msrsync/issues/12#issuecomment-428717403
https://github.com/jbd/msrsync/issues/7#issuecomment-386650406

**Comment by picturethisstudio** [comment]
This is the command i tried
 msrsync -p4 -P --stats -r "--exclude-from=/tmp/Isilon_Exclude_Directories" /mnt/projects/LIVE/LBM/EP1911/COMMON/ /mnt/AWS_S3_Bucket_m2adr/LIVE/LBM/EP1911/COMMON/

**Comment by picturethisstudio** [comment]
it's not reading the pattern file which is added

**Comment by jbd** [comment]
Please try vanilla rsync with the exact same parameters AND and read the different links I gave you in my first answer.

**Comment by picturethisstudio** [comment]
Tried that already. Normal rsync gives the expected results. Anyways, figured out the way to exclude. exclude from doesn't works but exclude worked for me. Hence need to give all those directories individually with exclude.
Thanks.
