### ISSUE TITLE
Missing SSH support

### ISSUE THREAD

**Issue by fatso83** [jbd/msrsync#18]
The main reason for me in using this tools was to speed ssh transfers, but this doesn't seem supported? 

```bash
$ time msrsync  -p8 --progress  --rsync ' -a -e "ssh -o Compression=no"'  myuser@timbuktu.kopseng.no:/mnt/data/Bilder/ Bilder_syncdir/syncdir/
Source 'myuser@timbuktu.kopseng.no:/mnt/data/Bilder/' is not a directory
```

**Comment by jbd** [comment]
Yes, sorry about that; From the first lines of the README :

`The main limitation is it does not handle remote source or target directory, they must be locally accessible (local disk, nfs/cifs/other mountpoint). I hope to address this in a near future.`

I don't have any plan to add this right now. You could check the others tools I mentionned in the README, maybe you'll find something useful.
