### ISSUE TITLE
How to copy files to remote server by msrsync

### ISSUE THREAD

**Issue by AaronCheungJiahao** [jbd/msrsync#2]
I try to use your tools to copy files to remote computers, but I am failed. Is there any way to help?
I don't want to use NAS ，or NFC or Samba

**Comment by jbd** [comment]
Hello,

unfortunately, msrsync only support locally mounted filesystems. From the README:

> The main limitation is it does not handle remote source or target directory, they must be locally accessible (local disk, nfs/cifs/other mountpoint). 

I'd like to address this in the future, but right now you're on your own with plain rsync or another tools like fpart/fpsync and parsync (see the README for links to those tools).

**Comment by dennyhalim** [comment]
please add this

**Comment by jmiezitis** [comment]
If people really want this and know what they are doing you can comment out lines 1212 to 1226 inclusively.
These are just after the comment:
    # dest may not exist, just as in rsync : "rsync -a src dst" will create
    # destination if it does not exist. But I prefer to create it here to handle
    # potential errors

So this action is going against the intent of @jbd but will allow you to use remote sources or destinations.  e.g.
msrsync -p2 --progress --rsync "-aS -e ssh" /local_src 192.168.0.10:/remote_dest
or
msrsync -p2 --progress --rsync "-aS -e ssh" 192.268.0.10:/remote_src /local_dest
