### ISSUE TITLE
delete option

### ISSUE THREAD

**Issue by otteydw** [jbd/msrsync#21]
I ran the msrync to try to replace an existing rsync command and got the error message

> error: Cannot use --delete option type with msrsync. It would lead to disaster :)

While I find the error message to be acceptable (in fact, this is the issue I'm trying to Google for solving in parallel rsyncs), it would be nice if the README of this repo discussed this limitation up front.  It would have saved me from the time spent downloading and testing it.

**Comment by jbd** [comment]
Hello,

thank you for reporting this issue. Maybe you'll be interested in the fpart/fpsync helper from https://github.com/martymac/fpart: it handles the --delete flags in parallel sync. Looks for option "-E" in the README.
