### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by serge2016** [jbd/msrsync#23]
Hello!

Does your tool support python3?

**Comment by yellowsoar** [comment]
It seems OK on python 3 via vermin testing.
https://pypi.org/project/vermin/
But might not OK on python 3.5.2  according to https://github.com/jbd/msrsync/pull/4?

**Comment by 3eka** [comment]
Seems native python 3 support is still missing?
Any ETA on fix?

Regards.

**Comment by jbd** [comment]
Hello,

I understand the frustration around python3 support in msrsync, sorry for that. No progress so far. In the meantime, you could have a look at carlilek's PR which seems to work for him : https://github.com/jbd/msrsync/pull/4.

I leave this issue open.

**Comment by jbd** [comment]
You can have a look at the msrsync3 script in the master branch. Please not that this project is not actively developed. I encourage you to look at the alternatives mentioned in the README.
