### ISSUE TITLE
Allowing remote hosts in destination

### ISSUE THREAD

**Issue by joehern** [jbd/msrsync#26]
I'd like to be able to specify user@host:/dir as a remote destination. The code appears to only allow local destinations. Is this just a matter of modifying  _check_srcs_dest ?

**Comment by jbd** [comment]
Hello,

> The code appears to only allow local destinations

You're correct. It would be a nice feature, but I won't implement it in the near future. 

This appears in the first paragraph of the README:

`The main limitation is it does not handle remote source or target directory, they must be locally accessible (local disk, nfs/cifs/other mountpoint). I hope to address this in a near future.`

You can have a look at fpart: https://github.com/martymac/fpart
