### ISSUE TITLE
SSH 

### ISSUE THREAD

**Issue by lotustechie** [jbd/msrsync#28]
Is there a way to pass an ssh source to the script?

`msrsync --rsync "-avzp --remove-source-files -e ssh" root@10.16.234.35:/mnt/Data/Media/Movies  /mnt/pools/A/A0/Data/Media`

**Comment by jbd** [comment]
Hi,

Sorry for the delay. 

`msrsync` does not handle remote locations. From the README:
```
The main limitation is it does not handle remote source or target directory, they must be locally accessible (local disk, nfs/cifs/other mountpoint).
```
I understand the frustration about this limitation. Best chance for you would be to have a look at the alternatives I suggested.

Jean-Baptiste
