### ISSUE TITLE
msrync with rsyncd

### ISSUE THREAD

**Issue by grinderx** [jbd/msrsync#29]
Hello,

Hope you are well and safe. I 'd like to ask whether it's possible to use msrsync with the rsync daemon in order to record the changes in the source and speed up the decision times for what needs to be synced or if this will confuse things for msrysnc. Thanks.

Best regards,
G

**Comment by jbd** [comment]
Hello,

sorry for the late answer. Unfortunatly, it's not possible to leverage the rsync daemon at the moment. You might want to look at fpsync tool from the fpart project in the meantime : https://github.com/martymac/fpart.
