### ISSUE TITLE
-r option not parsed? 

### ISSUE THREAD

**Issue by carlilek** [jbd/msrsync#3]
Unless I'm greatly mistaken, the -r flag is not being processed into --rsync. For example, I had -r '-W --delete --inplace' in my command, but it did not throw an exception on the --delete, and looking at the destination, it was definitely using temp files rather than using --inplace.

**Comment by jbd** [comment]
Good catch. Could you try https://github.com/jbd/msrsync/commit/b36f1dd59880de623e93300ff69415ac81bd4acf and see if everything is OK for you now ?

Thank you !

**Comment by carlilek** [comment]
Yup, that worked! Thanks!
