### ISSUE TITLE
please add the option for sing file or multi files

### ISSUE THREAD

**Issue by moerfutin** [jbd/msrsync#31]
When I tried to rsync one file from remote server, it said:

> Source 'user@IP:/dir/222.7z' is not a directory

**Comment by jbd** [comment]
Hello,

I won't implement this feature, you should try another tool. (Look at the README for suggestions).

You can have a look here : https://github.com/jbd/msrsync/issues?q=ssh
You can also try this suggestion: https://github.com/jbd/msrsync/issues/2#issuecomment-794499763
