### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by babvin** [jbd/msrsync#34]
Please make it compatible with Python3

sudo msrsync -p 8 -xa --progress --exclude /nfs / /nfs/k3s-wrkr02
/usr/bin/env: ‘python2’: No such file or directory

**Comment by jbd** [comment]
Hello,

you can have a look at the msrsync3 script in the master branch. Please not that this project is not actively developed. I encourage you to look at the alternatives mentioned in the README.
