### ISSUE TITLE
--delete flag

### ISSUE THREAD

**Issue by carlilek** [jbd/msrsync#5]
Can you explain why a --delete flag would be catastrophic with msrsync? Ideally I'd like to be able to use msrsync to create a backup from one enterprise NAS to another, but without the delete flag, that's not really feasible.

**Comment by jbd** [comment]
msrsync will crawl a filesystem and generate list of files for rsync to consume (using --files-from rsync option). Each list of files can spawn multiple directories, there is no control on that : crawl filesystem, generate list of N files or V bytes worth of data and feed rsync processes with it. 

If you're synchronizing /mnt/src to /mnt/dest for example, msrync will generate something like:

```
rsync -aS --numeric-ids --from0 --files-from=/tmp/list1 /mnt/src /mnt/dest
rsync -aS --numeric-ids --from0 --files-from=/tmp/list2 /mnt/src /mnt/dest
...
rsync -aS --numeric-ids --from0 --files-from=/tmp/list1024 /mnt/src /mnt/dest
```
Note the source and the destination on the rsync command line are always the same. Everything is coming from the file pointed by --files-from option. Now imagine having the --delete on each of those rsync command (running potentially in parallel) : each rsync will delete files that are not in the file pointed by the files-from option. That's what I'm calling "catastrophic" =) 

Is that clear enough ?

You can create a backup from one NAS to another by using two passes : one msrync to to the heavy lifting and then a classic rsync with the --delete option. That's why I did to migrate 1 PB+ of data between two NAS. Not optimal, but it's a working solution.

I urge you to have a look at [fpart](https://github.com/martymac/fpart) and its fpsync helper (check the msrync [README](https://github.com/jbd/msrsync/) file to have some pointers). The author was a colleague of mine (msrsync came after as a minimal python 2.6 solution for RHEL6 compatibility) and his tool is rock solid and actively developped : he implemented the --delete in parallel recently (you can have only one pass instead of two as shown before). See the -E option of fpart. From the README:

```
Note : several successive fpart runs can be launched using the above example;
you will perform incremental synchronizations. That is, deleted files from the
source directory will not be removed from destination unless rsync's --delete
option is used. Unfortunately, this option cannot be used with a list of files
(files that do not appear in the list are just ignored). To use the --delete
option in conjunction with fpart, you *have* to provide rsync's --files-from
option a list of directories (only); that can be performed using fpart's -E
option. 
```
His tool has been cited by members of AWS team:

http://docs.aws.amazon.com/solutions/latest/efs-to-efs-backup/considerations.html
https://fr.slideshare.net/AmazonWebServices/amazon-elastic-file-system-amazon-efs-for-file-storage

Don't get me wrong : I'm more than happy to receive feedback, bug reports and contributions for msrsync. But if you look a battle proof tested solution and *actively developed*, fpart/fpsync is the way to go in my opinion.

**Comment by carlilek** [comment]
That totally follows. Thanks! I knew there was some little bit I was missing. I'm using msrsync to prestage, but unfortunately I have so many files that I need something parallel just to get through the crawl in a reasonable amount of time for the diffs. 


--Ken



On Dec 31, 2017, at 1:57 PM, jbd <notifications@github.com> wrote:


msrsync will crawl a filesystem and generate list of files for rsync to consume (using --files-from rsync option). Each list of files can spawn multiple directories, there is no control on that : crawl filesystem, generate list of N files or V bytes
 worth of data and feed rsync processes with it.
If you're synchronizing /mnt/src to /mnt/dest for example, msrync will generate something like:
rsync -aS --numeric-ids --from0 --files-from=/tmp/list1 /mnt/src /mnt/dest
rsync -aS --numeric-ids --from0 --files-from=/tmp/list2 /mnt/src /mnt/dest
...
rsync -aS --numeric-ids --from0 --files-from=/tmp/list1024 /mnt/src /mnt/dest

Note the source and the destination on the rsync command line are always the same. Everything is coming from the file pointed by --files-from option. Now imagine having the --delete on each of those rsync command (running potentially in parallel)
 : each rsync will delete files that are not in the file pointed by the files-from option. That's what I'm calling "catastrophic" =)
Is that clear enough ?
You can create a backup from one NAS to another by using two passes : one msrync to to the heavy lifting and then a classic rsync with the --delete option. That's why I did to migrate 1 PB+ of data between two NAS. Not optimal, but it's a working
 solution.
I urge you to have a look at 
fpart and its fpsync helper (check the msrync 
README file to have some pointers). The author was a colleague of mine (msrsync came after as a minimal python 2.6 solution for RHEL6 compatibility) and his tool is rock solid and actively developped : he implemented the --delete in parallel recently (you
 can have only one pass instead of two as shown before). See the -E option of fpart. From the README:
Note : several successive fpart runs can be launched using the above example;
you will perform incremental synchronizations. That is, deleted files from the
source directory will not be removed from destination unless rsync's --delete
option is used. Unfortunately, this option cannot be used with a list of files
(files that do not appear in the list are just ignored). To use the --delete
option in conjunction with fpart, you *have* to provide rsync's --files-from
option a list of directories (only); that can be performed using fpart's -E
option. 

His tool has been cited by members of AWS team:
http://docs.aws.amazon.com/solutions/latest/efs-to-efs-backup/considerations.html
https://fr.slideshare.net/AmazonWebServices/amazon-elastic-file-system-amazon-efs-for-file-storage
Don't get me wrong : I'm more than happy to receive feedback, bug reports and contributions for msrsync. But if you look a battle proof tested solution and
actively developed, fpart/fpsync is the way to go in my opinion.
—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.







{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jbd/msrsync","title":"jbd/msrsync","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/jbd/msrsync" class="">https://github.com/jbd/msrsync</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jbd in #5: msrsync will crawl a filesystem and generate list of files for rsync to consume (using --files-from rsync option). Each list of files can spawn multiple directories, there is no control on that : crawl filesystem, generate list of N files or V bytes worth of data and feed rsync processes with it. \r\n\r\nIf you're synchronizing /mnt/src to /mnt/dest for example, msrync will generate something like:\r\n\r\n```\r\nrsync -aS --numeric-ids --from0 --files-from=/tmp/list1 /mnt/src /mnt/dest\r\nrsync -aS --numeric-ids --from0 --files-from=/tmp/list2 /mnt/src /mnt/dest\r\n...\r\nrsync -aS --numeric-ids --from0 --files-from=/tmp/list1024 /mnt/src /mnt/dest\r\n```\r\nNote the source and the destination on the rsync command line are always the same. Everything is coming from the file pointed by --files-from option. Now imagine having the --delete on each of those rsync command (running potentially in parallel) : each rsync will delete files that are not in the file pointed by the files-from option. That's what I'm calling \"catastrophic\" =) \r\n\r\nIs that clear enough ?\r\n\r\nYou can create a backup from one NAS to another by using two passes : one msrync to to the heavy lifting and then a classic rsync with the --delete option. That's why I did to migrate 1 PB+ of data between two NAS. Not optimal, but it's a working solution.\r\n\r\nI urge you to have a look at [fpart](<a href="https://github.com/martymac/fpart" class="">https://github.com/martymac/fpart</a>) and its fpsync helper (check the msrync [README](<a href="https://github.com/jbd/msrsync/" class="">https://github.com/jbd/msrsync/</a>) file to have some pointers). The author was a colleague of mine (msrsync came after as a minimal python 2.6 solution for RHEL6 compatibility) and his tool is rock solid and actively developped : he implemented the --delete in parallel recently (you can have only one pass instead of two as shown before). See the -E option of fpart. From the README:\r\n\r\n```\r\nNote : several successive fpart runs can be launched using the above example;\r\nyou will perform incremental synchronizations. That is, deleted files from the\r\nsource directory will not be removed from destination unless rsync's --delete\r\noption is used. Unfortunately, this option cannot be used with a list of files\r\n(files that do not appear in the list are just ignored). To use the --delete\r\noption in conjunction with fpart, you *have* to provide rsync's --files-from\r\noption a list of directories (only); that can be performed using fpart's -E\r\noption. \r\n```\r\nHis tool has been cited by members of AWS team:\r\n\r\<a href="nhttp://docs.aws.amazon.com/solutions/latest/efs-to-efs-backup/considerations.html\r\nhttps://fr.slideshare.net/AmazonWebServices/amazon-elastic-file-system-amazon-efs-for-file-storage\r\n\r\nDon't" class="">nhttp://docs.aws.amazon.com/solutions/latest/efs-to-efs-backup/considerations.html\r\nhttps://fr.slideshare.net/AmazonWebServices/amazon-elastic-file-system-amazon-efs-for-file-storage\r\n\r\nDon't</a> get me wrong : I'm more than happy to receive feedback, bug reports and contributions for msrsync. But if you look a battle proof tested solution and *actively developed*, fpart/fpsync is the way to go in my opinion."}],"action":{"name":"View Issue","url":"<a href="https://github.com/jbd/msrsync/issues/5#issuecomment-354619103" class="">https://github.com/jbd/msrsync/issues/5#issuecomment-354619103</a>"}}}

**Comment by carlilek** [comment]
Historically I've used an ls | parallel -q rsync blah blah blah, but that tends to break down after a while with a deeply nested file tree and requires a lot of babysitting. Plus msrsync is much more foolproof... btw, was pointed towards your tool by people
 at Qumulo. 


--Ken



On Dec 31, 2017, at 1:59 PM, Carlile, Ken <carlilek@janelia.hhmi.org> wrote:



That totally follows. Thanks! I knew there was some little bit I was missing. I'm using msrsync to prestage, but unfortunately I have so many files that I need something parallel just to get through the crawl in a reasonable amount of time for the diffs. 


--Ken



On Dec 31, 2017, at 1:57 PM, jbd <notifications@github.com> wrote:


msrsync will crawl a filesystem and generate list of files for rsync to consume (using --files-from rsync option). Each list of files can spawn multiple directories, there is no control on that : crawl filesystem, generate list of N files or V bytes
 worth of data and feed rsync processes with it.
If you're synchronizing /mnt/src to /mnt/dest for example, msrync will generate something like:
rsync -aS --numeric-ids --from0 --files-from=/tmp/list1 /mnt/src /mnt/dest
rsync -aS --numeric-ids --from0 --files-from=/tmp/list2 /mnt/src /mnt/dest
...
rsync -aS --numeric-ids --from0 --files-from=/tmp/list1024 /mnt/src /mnt/dest

Note the source and the destination on the rsync command line are always the same. Everything is coming from the file pointed by --files-from option. Now imagine having the --delete on each of those rsync command (running potentially in parallel)
 : each rsync will delete files that are not in the file pointed by the files-from option. That's what I'm calling "catastrophic" =)
Is that clear enough ?
You can create a backup from one NAS to another by using two passes : one msrync to to the heavy lifting and then a classic rsync with the --delete option. That's why I did to migrate 1 PB+ of data between two NAS. Not optimal, but it's a working
 solution.
I urge you to have a look at 
fpart and its fpsync helper (check the msrync 
README file to have some pointers). The author was a colleague of mine (msrsync came after as a minimal python 2.6 solution for RHEL6 compatibility) and his tool is rock solid and actively developped : he implemented the --delete in parallel recently (you
 can have only one pass instead of two as shown before). See the -E option of fpart. From the README:
Note : several successive fpart runs can be launched using the above example;
you will perform incremental synchronizations. That is, deleted files from the
source directory will not be removed from destination unless rsync's --delete
option is used. Unfortunately, this option cannot be used with a list of files
(files that do not appear in the list are just ignored). To use the --delete
option in conjunction with fpart, you *have* to provide rsync's --files-from
option a list of directories (only); that can be performed using fpart's -E
option. 

His tool has been cited by members of AWS team:
http://docs.aws.amazon.com/solutions/latest/efs-to-efs-backup/considerations.html
https://fr.slideshare.net/AmazonWebServices/amazon-elastic-file-system-amazon-efs-for-file-storage
Don't get me wrong : I'm more than happy to receive feedback, bug reports and contributions for msrsync. But if you look a battle proof tested solution and
actively developed, fpart/fpsync is the way to go in my opinion.
—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.







{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jbd/msrsync","title":"jbd/msrsync","subtitle":"GitHub repository","main_image_url":"<a href="<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>" class=""><a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a></a>","avatar_image_url":"<a href="<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>" class=""><a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a></a>","action":{"name":"Open in GitHub","url":"<a href="<a href="https://github.com/jbd/msrsync" class="">https://github.com/jbd/msrsync</a>" class=""><a href="https://github.com/jbd/msrsync" class="">https://github.com/jbd/msrsync</a></a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jbd in #5: msrsync will crawl a filesystem and generate list of files for rsync to consume (using --files-from rsync option). Each list of files can spawn multiple directories, there is no control on that : crawl filesystem, generate list of N files or V bytes worth of data and feed rsync processes with it. \r\n\r\nIf you're synchronizing /mnt/src to /mnt/dest for example, msrync will generate something like:\r\n\r\n```\r\nrsync -aS --numeric-ids --from0 --files-from=/tmp/list1 /mnt/src /mnt/dest\r\nrsync -aS --numeric-ids --from0 --files-from=/tmp/list2 /mnt/src /mnt/dest\r\n...\r\nrsync -aS --numeric-ids --from0 --files-from=/tmp/list1024 /mnt/src /mnt/dest\r\n```\r\nNote the source and the destination on the rsync command line are always the same. Everything is coming from the file pointed by --files-from option. Now imagine having the --delete on each of those rsync command (running potentially in parallel) : each rsync will delete files that are not in the file pointed by the files-from option. That's what I'm calling \"catastrophic\" =) \r\n\r\nIs that clear enough ?\r\n\r\nYou can create a backup from one NAS to another by using two passes : one msrync to to the heavy lifting and then a classic rsync with the --delete option. That's why I did to migrate 1 PB+ of data between two NAS. Not optimal, but it's a working solution.\r\n\r\nI urge you to have a look at [fpart](<a href="<a href="https://github.com/martymac/fpart" class="">https://github.com/martymac/fpart</a>" class=""><a href="https://github.com/martymac/fpart" class="">https://github.com/martymac/fpart</a></a>) and its fpsync helper (check the msrync [README](<a href="<a href="https://github.com/jbd/msrsync/" class="">https://github.com/jbd/msrsync/</a>" class=""><a href="https://github.com/jbd/msrsync/" class="">https://github.com/jbd/msrsync/</a></a>) file to have some pointers). The author was a colleague of mine (msrsync came after as a minimal python 2.6 solution for RHEL6 compatibility) and his tool is rock solid and actively developped : he implemented the --delete in parallel recently (you can have only one pass instead of two as shown before). See the -E option of fpart. From the README:\r\n\r\n```\r\nNote : several successive fpart runs can be launched using the above example;\r\nyou will perform incremental synchronizations. That is, deleted files from the\r\nsource directory will not be removed from destination unless rsync's --delete\r\noption is used. Unfortunately, this option cannot be used with a list of files\r\n(files that do not appear in the list are just ignored). To use the --delete\r\noption in conjunction with fpart, you *have* to provide rsync's --files-from\r\noption a list of directories (only); that can be performed using fpart's -E\r\noption. \r\n```\r\nHis tool has been cited by members of AWS team:\r\n\r\<a href="<a href="nhttp://docs.aws.amazon.com/solutions/latest/efs-to-efs-backup/considerations.html\r\nhttps://fr.slideshare.net/AmazonWebServices/amazon-elastic-file-system-amazon-efs-for-file-storage\r\n\r\nDon't" class="">nhttp://docs.aws.amazon.com/solutions/latest/efs-to-efs-backup/considerations.html\r\nhttps://fr.slideshare.net/AmazonWebServices/amazon-elastic-file-system-amazon-efs-for-file-storage\r\n\r\nDon't</a>" class=""><a href="nhttp://docs.aws.amazon.com/solutions/latest/efs-to-efs-backup/considerations.html\r\nhttps://fr.slideshare.net/AmazonWebServices/amazon-elastic-file-system-amazon-efs-for-file-storage\r\n\r\nDon't" class="">nhttp://docs.aws.amazon.com/solutions/latest/efs-to-efs-backup/considerations.html\r\nhttps://fr.slideshare.net/AmazonWebServices/amazon-elastic-file-system-amazon-efs-for-file-storage\r\n\r\nDon't</a></a> get me wrong : I'm more than happy to receive feedback, bug reports and contributions for msrsync. But if you look a battle proof tested solution and *actively developed*, fpart/fpsync is the way to go in my opinion."}],"action":{"name":"View Issue","url":"<a href="<a href="https://github.com/jbd/msrsync/issues/5#issuecomment-354619103" class="">https://github.com/jbd/msrsync/issues/5#issuecomment-354619103</a>" class=""><a href="https://github.com/jbd/msrsync/issues/5#issuecomment-354619103" class="">https://github.com/jbd/msrsync/issues/5#issuecomment-354619103</a></a>"}}}

**Comment by jbd** [comment]
To this date, msrsync and fpart both lack parallel filesystem crawling. Depending on the nature of your dataset (number of files, size, nas vendor, network, you name it) it can make a huge difference in some cases. 

You can check a discussion I initiated about parallel file crawling on the (very nice) [duc project](https://github.com/zevv/duc/): https://github.com/zevv/duc/issues/161. I gave some [numbers](https://github.com/zevv/duc/issues/161#issuecomment-269785068). Maybe you'll find something interesting here. 

I have used msrsync and fpart to transfer hundreds of millions files between NAS and even if I didn't had anything to transfer, it tooks up to two days (depending on the NAS production load) just to crawl the filesystem. No real difference here between the two tools here.

> btw, was pointed towards your tool by people at Qumulo. 

Always nice to read, thank you !

**Comment by jbd** [comment]
FWIW, fpart has implemented the rsync --delete option (-E) : https://github.com/martymac/fpart.
