### ISSUE TITLE
UnboundLocalError: local variable 'rsync_result' referenced before assignment

### ISSUE THREAD

**Issue by ipsec** [jbd/msrsync#6]
msrsync --stats -d -p 4 --rsync "-ravutg --exclude=lost+found" /source/ /destination/
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./msrsync", line 824, in rsync_worker
    rsync_mon_result = {"type": TYPE_RSYNC, "rsync_result": rsync_result, "size": bucket_size, "files_nr": bucket_files_nr, "jq_size": jobs_queue.qsize()}
UnboundLocalError: local variable 'rsync_result' referenced before assignment

**Comment by jbd** [comment]
Hello,

thank your for opening this issue. I don't have a lot of time to address this problem (@carlilek has a PR and an issue that have been pending for months...), but could you just confirm that you are using the master branch ? 

For now, I'm not able to reproduce the issue. Does it happen immediatly of after some files have already been transfered ?

**Comment by stevelawrence66** [comment]
I'm able to reproduce it when using the -d (dry-run) parameter, but when performing an actual transfer - its fine. It happens immediately, produces no output and dumps you back to a prompt.

**Comment by jbd** [comment]
Thank you for getting back to me. I don't understand why I wasn't able to reproduce in the first place, this is a stupid bug. I've just fiex in in https://github.com/jbd/msrsync/commit/1352df85a7cf2a908692ba1142c39a9cb6bd8f04.
